projeto_pd/accounts/urls.py
""" Define padões de url para contas """

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Inclui Urls de autenticação default
    path('', include('django.contrib.auth.urls')),
    # Pagina de cadastros
    path('register', views.register, name='register'),
]

projeto_pd/learning_logs/urls.py
""" Define padrões de url para learning logs """

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Página Inicial
    path('', views.index, name='index'),
    # Pagina que mostra todos os tópicos
    path('topicos/', views.topicos, name='topicos'),
    path('topicos/<int:id_topico>/', views.topico, name='topico'),
    # Página para adicionar um tópico novo
    path('novo_topico/', views.novo_topico, name='novo_topico'),
    # Página para adicionar uma entrada nova
    path('nova_entrada/<int:id_topico>/', views.nova_entrada, name='nova_entrada'),
    # Página para editar uma entrada
    path('editar_entrada/<int:id_entrada>/', views.editar_entrada, name='editar_entrada'),
]

projeto_pd/projeto_pd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

projeto_pd/accounts/models.py
from django.db import models

# Create your models here.

projeto_pd/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topico(models.Model):
    """ Um tópico que o usuário está aprendendo """
    text = models.CharField(max_length=200)
    data_add = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
class Entrada(models.Model):
    """ Algo específico aprendido sobre um tópico """
    topico = models.ForeignKey(Topico, on_delete=models.CASCADE)
    text = models.TextField()
    data_add = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entradas'

    def __str__(self):
        """ Retorna uma string simples representando a entrada """
        if len(self.texto) > 50:
            return f'{self.texto[:50]}...'
        else:
            return self.texto

projeto_pd/learning_logs/forms.py
from django import forms

from .models import Topico, Entrada

class FormularioTopico(forms.ModelForm):
    class Meta:
        model = Topico
        fields = ['text']
        labels = {'text': ''}

class EntradaFormulario(forms.ModelForm):
    class Meta:
        model = Entrada
        fields = ['text']
        labels = {'text' : ''}
        widgets = {'text' : forms.Textarea(attrs={'cols' : 80})}

projeto_pd/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """ Cadastra um usuário novo """
    if request.method != 'POST':
        # Exibe o formulário em brando de cadastro
        form = UserCreationForm()
    else:
        # Processa o formulário preenchido
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Faz o login do usuário e o redirecona para a página inicial
            login(request, new_user)
            return redirect('learning_logs:index')
        
    # Exibe um formulário em brando ou inválido
    context = {'form' : form}
    return render(request, 'registration/register.html', context)

projeto_pd/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topico, Entrada
from .forms import FormularioTopico, EntradaFormulario

def checa_proprietario_topico(request):
    if topico.owner != request.user:
        raise Http404

# Create your views here.
def index(request):
    """ A pagina inicial para o registro de aprendizagem """
    return render(request, 'learning_logs/index.html')


@login_required
def topicos(request):
    """ Mostra todos os tópicos """
    tp = Topico.objects.filter(owner=request.user).order_by('data_add')
    contexto = {'topicos' : tp}
    return render(request, 'learning_logs/topicos.html', contexto)


@login_required
def topico(request, id_topico):
    """ Mostra um único tópico e todas as sua entradas"""
    topico = Topico.objects.get(id=id_topico)
    # Verifica se o tópico pertence ao usuário atual
    checa_proprietario_topico(request)
    entradas = topico.entrada_set.order_by('-data_add')
    contexto = {'topico' : topico, 'entradas' : entradas}
    return render(request, 'learning_logs/topico.html', contexto)


@login_required
def novo_topico(request):
    """ Adiiona um novo tópico """
    if request.method != 'POST':
        # Nenhum dado enviado; cria um formulário em branco
        form = FormularioTopico()
    else:
        # Dados POST enviados: processa os dados
        form = FormularioTopico(data=request.POST)
        if form.is_valid():
            novo_topico = form.save(commit=False)
            novo_topico.owner = request.user
            novo_topico.save()
            return redirect('learning_logs:topicos')
        
    # Exibe um formulário em branco ou inválido
    context = {'form' : form}
    return render(request, 'learning_logs/novo_topico.html', context)


@login_required
def nova_entrada(request, id_topico):
    """ Adicinona uma entrada nova para um tópico específico """
    topico = Topico.objects.get(id=id_topico)

    if request.method != 'POST':
        # Nenhum dado enviado; cria um formulário em branco
        form = EntradaFormulario()
    else:
        # Dados POST enviados; processa os dados
        form = EntradaFormulario(data=request.POST)
        if form.is_valid():
            nova_entrada = form.save(commit=False)
            nova_entrada.topico = topico
            nova_entrada.save()
            return redirect('learning_logs:topico', id_topico=id_topico)
    
    # Exibe um formulário em branco ou inválido
    context = {'topico' : topico, 'form' : form}
    return render(request, 'learning_logs/nova_entrada.html', context)


@login_required
def editar_entrada(request, id_entrada):
    """ Edita uma entrada existente """
    entrada = Entrada.objects.get(id=id_entrada)
    topico = entrada.topico
    checa_proprietario_topico(request)

    if request.method != 'POST':
        # Requisição inicial; pre-preenche o formulário com a entrada atual.
        form = EntradaFormulario(instance=entrada)
    else:
        # Dados POST enviados; processa os dados
        form = EntradaFormulario(instance=entrada, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topico', id_topico=topico.id)
    
    context = {'entrada' : entrada, 'topico' : topico, 'form' : form}
    return render(request, 'learning_logs/editar_entrada.html', context)

projeto_pd/learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topicos' %}"> Tópicos</a>
                    </li>
                </ul><!-- Fim dos links no lado esquerdo da barra de navegação -->

                <!-- Links relacionados à conta -->
                <ul>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text me-2">Olá, {{ user.username }}</span>
                        </li>
                        
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:register' %}">Registrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul><!-- Fim dos links relacionados à conta -->

                {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button name="submit" class="btn btn-outline-secondary btn-sm">Logout</button>
                    </form>
                {% endif %}

            </div><!-- Fecha as partes recolhiveis da barra de navegação -->
        </div><!-- Fecha o container da barra de navegação -->
    </nav><!-- Fim da barra de navegação -->

    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

projeto_pd/learning_logs/templates/learning_logs/editar_entrada.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'learning_logs/base.html' %}

    {% block content %}
        <p><a href="{% url 'learning_logs:topico' topico.id %}">{{ topico }}</a></p>
        <p>Editar entrada:</p>

        <form action="{% url 'learning_logs:editar_entrada' entrada.id %}" method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <button name="submit">Salvar Alterações</button>
        </form>
    {% endblock content %}
</body>
</html>

projeto_pd/learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Acompanhe Seu Aprendizado</h1>
            <p class="lead">Faça seus proprios registros de aprendizagem, 
                e mantenha uma lista dos tópicos que você está aprendendo.
                Enquanto voce aprende sobre um tópico, faça as entradas
                que voce aprendeu.
            </p>
            
            <a class="btn btn-primary btn-lg mt-1"
                href="{% url 'accounts:register' %}">Registrar &raquo;</a>
        </div>
    </div>
{% endblock page_header %}

projeto_pd/learning_logs/templates/learning_logs/nova_entrada.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'learnig_logs/base.html' %}

    {% block content%}
        <p><a href="{% url 'learning_logs:topico' topico.id %}">{{ topico }}</a></p>

        <p>Adicionando uma nova entrada:</p>
        <form action="{% url 'learning_logs:nova_entrada' topico.id %}" method="post">
            {% csrf_token %}
            {{ form.as_div }}
            <button name="submit">Adicionar Entrada</button>
        </form>

    {% endblock content %}
</body>
</html>

projeto_pd/learning_logs/templates/learning_logs/novo_topico.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    { extends 'learning_logs/base.html'}

    {% block content %}
        <p>Adicionando um novo tópico</p>

        <form action="{% url 'learning_logs:novo_topico' %}" method="post">
            {% csrf_token %}
            {{form.as_div}}
            <button name="submit">Adicionar Tópico</button>
        </form>

    {% endblock content %}
</body>
</html>

projeto_pd/learning_logs/templates/learning_logs/topico.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Tópico: {{topico.text}}</h1>
{% endblock page_header %}

{% block content %}

    <p>
        <a href="{% url 'learning_logs:nova_entrada' topico.id %}">Adicionar Nova Entrada</a>
    </p>
    
    {% for entrada in entradas %}
        <div class="card mb-3">
            <!-- Cabeçalho do card com timestamp e link de edição -->
            <h4 class="card-header">
                {{ entrada.data_add|date:'M D, Y H:i' }}
                <small><a href="{% url 'learning_logs:editar_entrada' entrada.id %}">Editar Entrada</a></small>
            </h4>
            <!-- Corpo do card com texto de entrada -->
            <div class="card-body">
                {{ entrada.text|linebreaks }}
            </div>

        </div>
    {% empty %}
        <p>Não existem entradas neste tópico</p>
        
    {% endfor %}


{% endblock content %}

projeto_pd/learning_logs/templates/learning_logs/topicos.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Tópicos</h1>
{% endblock page_header %}

{% block content %}
    
    <ul class="list-group border-botton pb-2 mb-4">
        {% for topico in topicos %}
            <li class="list-group-item border-0">
                <a href="{% url 'learning_logs:topico' topico.id %}">{{topico.text}}</a>
            </li>
        {% empty %}
            <li class="list-group-item border-0">Não existem topicos adicionados!</li>
        {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:novo_topico' %}">Adicionar um novo tópico</a>

{% endblock content %}